import { v4 as uuidv4 } from 'uuid';
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc.js';
import timezone from 'dayjs/plugin/timezone.js';

dayjs.extend(utc);
dayjs.extend(timezone);

function d(daysAgo) {
  return dayjs().tz('Asia/Ho_Chi_Minh').subtract(daysAgo, 'day').format('YYYY-MM-DDTHH:mm:ss');
}

function future(daysFromNow) {
  return dayjs().tz('Asia/Ho_Chi_Minh').add(daysFromNow, 'day').format('YYYY-MM-DD');
}

function past(daysAgo) {
  return dayjs().tz('Asia/Ho_Chi_Minh').subtract(daysAgo, 'day').format('YYYY-MM-DD');
}

function historyEntry(by, action, changes = {}, note = '') {
  return { at: d(0), by, action, changes, note };
}

const nhanVien = [
  { id: '1', maNV: 'admin', tenNV: 'Admin', role: 'admin', active: true },
  { id: '2', maNV: 'nv001', tenNV: 'Nguyễn Văn An', role: 'staff', active: true },
  { id: '3', maNV: 'nv002', tenNV: 'Trần Thị Bình', role: 'staff', active: true },
  { id: '4', maNV: 'nv003', tenNV: 'Lê Hoàng Cường', role: 'staff', active: true },
];

const warranties = [
  {
    id: uuidv4(),
    stt: 1,
    soChungTu: '01012026NTPC1',
    ngayNhan: d(12),
    maNhanVien: 'admin',
    khachHang: 'Phạm Minh Đức',
    soDienThoai: '0901234567',
    diaChi: 'Đồng Nai',
    tenHang: 'Màn hình Gaming MSI MAG 245F X24',
    soSeri: 'BC8M016104747',
    cauHinh: '24.5" IPS 180Hz',
    loiLucNhan: 'Một điểm chết góc phải trên cùng',
    phuKien: 'Full box',
    chiPhi: 0,
    baoHanh: '36 tháng',
    loaiPhieu: 'nhan_bao_hanh',
    baoGiaSau: false,
    loaiXuLy: 'bao_hanh',
    loaiXuLyKhac: '',
    ghiChu: '',
    ngayMua: past(120),
    ngayHenTra: future(2),
    ngayTra: null,
    trangThai: 'dang_xu_ly',
    uuTien: true,
    supplierStatus: 'none',
    supplierIdCurrent: null,
    sentSupplierAt: '',
    expectedReturnSupplierAt: '',
    history: [historyEntry('admin', 'create', {}, 'Tạo phiếu bảo hành')],
    createdAt: d(12),
    updatedAt: d(12),
    deletedAt: null,
  },
  {
    id: uuidv4(),
    stt: 2,
    soChungTu: '02012026NTPC1',
    ngayNhan: d(8),
    maNhanVien: 'nv001',
    khachHang: 'Hoàng Thị Mai',
    soDienThoai: '0912345678',
    diaChi: 'Biên Hòa',
    tenHang: 'CPU AMD Ryzen 7 7800X3D',
    soSeri: 'AMD7800X3D001',
    cauHinh: '8 nhân 16 luồng',
    loiLucNhan: 'Không boot được, quạt quay nhưng không lên hình',
    phuKien: 'Hộp và tản nhiệt',
    chiPhi: 0,
    baoHanh: '36 tháng',
    loaiPhieu: 'nhan_bao_hanh',
    baoGiaSau: false,
    loaiXuLy: 'bao_hanh',
    loaiXuLyKhac: '',
    ghiChu: 'Khách mua tại NTPC',
    ngayMua: past(90),
    ngayHenTra: future(6),
    ngayTra: null,
    trangThai: 'cho_lien_he',
    uuTien: false,
    supplierStatus: 'none',
    supplierIdCurrent: null,
    sentSupplierAt: '',
    expectedReturnSupplierAt: '',
    history: [historyEntry('nv001', 'create', {}, 'Tạo phiếu bảo hành')],
    createdAt: d(8),
    updatedAt: d(8),
    deletedAt: null,
  },
  {
    id: uuidv4(),
    stt: 3,
    soChungTu: '03012026NTPC1',
    ngayNhan: d(5),
    maNhanVien: 'nv002',
    khachHang: 'Vũ Đức Anh',
    soDienThoai: '0923456789',
    diaChi: '',
    tenHang: 'RAM Corsair Vengeance DDR5 32GB',
    soSeri: 'CORSAIR32G001',
    cauHinh: 'DDR5 5600MHz',
    loiLucNhan: 'Máy báo lỗi RAM slot 2, không nhận đủ dung lượng',
    phuKien: '2 thanh RAM',
    chiPhi: 0,
    baoHanh: 'Lifetime',
    loaiPhieu: 'nhan_bao_hanh',
    baoGiaSau: false,
    loaiXuLy: 'bao_hanh',
    loaiXuLyKhac: '',
    ghiChu: '',
    ngayMua: past(60),
    ngayHenTra: future(9),
    ngayTra: null,
    trangThai: 'dang_xu_ly',
    uuTien: false,
    supplierStatus: 'none',
    supplierIdCurrent: null,
    sentSupplierAt: '',
    expectedReturnSupplierAt: '',
    history: [historyEntry('nv002', 'create', {}, 'Tạo phiếu bảo hành')],
    createdAt: d(5),
    updatedAt: d(5),
    deletedAt: null,
  },
  {
    id: uuidv4(),
    stt: 4,
    soChungTu: '04012026NTPC1',
    ngayNhan: d(20),
    maNhanVien: 'nv003',
    khachHang: 'Bùi Quang Huy',
    soDienThoai: '0945678901',
    diaChi: '',
    tenHang: 'GPU Nvidia RTX 4070 Ti Super',
    soSeri: 'NVIDIA4070TS001',
    cauHinh: '16GB GDDR6X',
    loiLucNhan: 'Màn hình bị artifact, driver crash liên tục',
    phuKien: 'Card, hộp và phụ kiện',
    chiPhi: 0,
    baoHanh: '36 tháng',
    loaiPhieu: 'nhan_bao_hanh',
    baoGiaSau: false,
    loaiXuLy: 'bao_hanh',
    loaiXuLyKhac: '',
    ghiChu: 'Cần kiểm tra kỹ VRAM',
    ngayMua: past(100),
    ngayHenTra: past(6),
    ngayTra: null,
    trangThai: 'dang_xu_ly',
    uuTien: true,
    supplierStatus: 'none',
    supplierIdCurrent: null,
    sentSupplierAt: '',
    expectedReturnSupplierAt: '',
    history: [historyEntry('nv003', 'create', {}, 'Tạo phiếu bảo hành')],
    createdAt: d(20),
    updatedAt: d(20),
    deletedAt: null,
  },
  {
    id: uuidv4(),
    stt: 5,
    soChungTu: '05012026NTPC1',
    ngayNhan: d(18),
    maNhanVien: 'admin',
    khachHang: 'Đặng Thị Hương',
    soDienThoai: '0934567890',
    diaChi: '',
    tenHang: 'SSD Kingston NV2 1TB',
    soSeri: 'KINGNV21T001',
    cauHinh: 'NVMe Gen4',
    loiLucNhan: 'Tốc độ đọc chậm bất thường, thường xuyên treo máy',
    phuKien: 'SSD và hộp',
    chiPhi: 0,
    baoHanh: '36 tháng',
    loaiPhieu: 'nhan_bao_hanh',
    baoGiaSau: false,
    loaiXuLy: 'bao_hanh',
    loaiXuLyKhac: '',
    ghiChu: '',
    ngayMua: past(80),
    ngayHenTra: past(3),
    ngayTra: past(1),
    trangThai: 'da_tra',
    uuTien: false,
    supplierStatus: 'returned',
    supplierIdCurrent: null,
    sentSupplierAt: '',
    expectedReturnSupplierAt: '',
    history: [
      historyEntry('admin', 'create', {}, 'Tạo phiếu bảo hành'),
      { at: d(1), by: 'admin', action: 'tra_hang', changes: { trangThai: { from: 'dang_xu_ly', to: 'da_tra' } }, note: 'Đã trả hàng cho khách' },
    ],
    createdAt: d(18),
    updatedAt: d(1),
    deletedAt: null,
  },
  {
    id: uuidv4(),
    stt: 6,
    soChungTu: '06012026NTPC1',
    ngayNhan: d(10),
    maNhanVien: 'nv001',
    khachHang: 'Lê Thị Lan',
    soDienThoai: '0956789012',
    diaChi: '',
    tenHang: 'Chuột Logitech G Pro X Superlight',
    soSeri: 'LOGIGPROX001',
    cauHinh: 'Wireless 25K DPI',
    loiLucNhan: 'Click đúp chuột phải, sensor không ổn định',
    phuKien: 'Chuột và dây sạc',
    chiPhi: 0,
    baoHanh: '24 tháng',
    loaiPhieu: 'nhan_bao_hanh',
    baoGiaSau: false,
    loaiXuLy: 'bao_hanh',
    loaiXuLyKhac: '',
    ghiChu: '',
    ngayMua: past(150),
    ngayHenTra: past(2),
    ngayTra: null,
    trangThai: 'huy',
    uuTien: false,
    supplierStatus: 'none',
    supplierIdCurrent: null,
    sentSupplierAt: '',
    expectedReturnSupplierAt: '',
    history: [
      historyEntry('nv001', 'create', {}, 'Tạo phiếu bảo hành'),
      { at: d(2), by: 'nv001', action: 'status', changes: { trangThai: { from: 'dang_xu_ly', to: 'huy' } }, note: 'Hủy theo yêu cầu khách hàng' },
    ],
    createdAt: d(10),
    updatedAt: d(2),
    deletedAt: null,
  },
];

export { warranties, nhanVien };
